// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// findStart
DateVector findStart(CharacterVector exp_key, DateVector start_int, DateVector end_int, CharacterVector trans_key, DateVector trans_date);
RcppExport SEXP _expstudies_findStart(SEXP exp_keySEXP, SEXP start_intSEXP, SEXP end_intSEXP, SEXP trans_keySEXP, SEXP trans_dateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type exp_key(exp_keySEXP);
    Rcpp::traits::input_parameter< DateVector >::type start_int(start_intSEXP);
    Rcpp::traits::input_parameter< DateVector >::type end_int(end_intSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type trans_key(trans_keySEXP);
    Rcpp::traits::input_parameter< DateVector >::type trans_date(trans_dateSEXP);
    rcpp_result_gen = Rcpp::wrap(findStart(exp_key, start_int, end_int, trans_key, trans_date));
    return rcpp_result_gen;
END_RCPP
}
// makeDays
DataFrame makeDays(CharacterVector record_key, DateVector record_start, IntegerVector record_days, int final_size);
RcppExport SEXP _expstudies_makeDays(SEXP record_keySEXP, SEXP record_startSEXP, SEXP record_daysSEXP, SEXP final_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type record_key(record_keySEXP);
    Rcpp::traits::input_parameter< DateVector >::type record_start(record_startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type record_days(record_daysSEXP);
    Rcpp::traits::input_parameter< int >::type final_size(final_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(makeDays(record_key, record_start, record_days, final_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_expstudies_findStart", (DL_FUNC) &_expstudies_findStart, 5},
    {"_expstudies_makeDays", (DL_FUNC) &_expstudies_makeDays, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_expstudies(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
