# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findStart <- function(exp_key, start_int, end_int, trans_key, trans_date) {
    .Call(`_expstudies_findStart`, exp_key, start_int, end_int, trans_key, trans_date)
}

