# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find the correct interval/key combination for start intervals.
#'
#' @param exp_key sorted key column.
#' @param start_int start_intervals that are are sorted within their keys
#' @param end_int end_intervals that are are sorted because start_int is sorted.
#' @param trans_key that must have a matching interval. This is guaranteed by the R code before calling findStart.
#' @param trans_date sorted date column.
findStart <- function(exp_key, start_int, end_int, trans_key, trans_date) {
    .Call(`_expstudies_findStart`, exp_key, start_int, end_int, trans_key, trans_date)
}

#' Create a DataFrame with all dates in the exposure period for each key
#'
#' @param record_key Vector of keys from the input record
#' @param record_start Vector of start dates from the input record
#' @param record_days Vector containing the number of days in the interval for a row in a record
#' @param final_size Sum of days in all intervals, used to initialize the DataFrame that is returned.
makeDays <- function(record_key, record_start, record_days, final_size) {
    .Call(`_expstudies_makeDays`, record_key, record_start, record_days, final_size)
}

